# fly.toml app configuration file generated for checkout-ui-extensions-app on 2023-06-23T18:32:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "checkout-ui-extensions-app"
primary_region = "nrt"

[env]
  PORT = "8081"
  HOST = "https://checkout-ui-extensions-app.fly.dev/"
  SCOPES = "write_products"
  SHOPIFY_API_KEY = "252ed66230672934fddc76f6c8b549bf"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
